### ISSUE TITLE
Build process complains about multiple providers for libunwind

### ISSUE THREAD

**Issue by madscientist42** [kraj/meta-clang#82]
Using Sumo to build for an aarch64 target...

ERROR: Multiple .bb files are due to be built which each provide libunwind:##########################################                                                                                                                       | ETA:  0:00:00
  /home/fearl/g2_wear_build/build/../meta/recipes-support/libunwind/libunwind_1.2.1.bb
  /home/fearl/g2_wear_build/build/../meta-clang/recipes-devtools/clang/libcxx_git.bb
A list of tasks depending on these providers is shown and may help explain where the dependency comes from.
/home/fearl/g2_wear_build/build/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique dependees:
  /home/fearl/g2_wear_build/build/../meta-wgv/recipes-wgv/wgv/wg-components.bb:do_prepare_recipe_sysroot
  /home/fearl/g2_wear_build/build/../meta-wgv/recipes-wgv/wgv/wg-components.bb:do_package
/home/fearl/g2_wear_build/build/../meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique dependees:
  /home/fearl/g2_wear_build/build/../meta-ambarella/recipes-core/ambarella/oryx_1.5.9.bb:do_prepare_recipe_sysroot
  /home/fearl/g2_wear_build/build/../meta-ambarella/recipes-core/ambarella/oryx_1.5.9.bb:do_package
It could be that one recipe provides something the other doesn't and should. The following provider and runtime provider differences may be helpful.
/home/fearl/g2_wear_build/build/../meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique provides:
  
/home/fearl/g2_wear_build/build/../meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique rprovides:
  libunwind-dbg
  ^libunwind-locale-.*
  libunwind-doc
  libunwind-locale
  libunwind-dev
  libunwind-staticdev
/home/fearl/g2_wear_build/build/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique provides:
  libcxx
/home/fearl/g2_wear_build/build/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique rprovides:
  libcxx-dev
  libcxx
  libcxx-doc
  libcxx-locale
  libcxx-dbg
  ^libcxx-locale-.*
  libcxx-staticdev

That's an issue where one would want/need to install things for a specific application that wants clang/LLVM for sanitizer support, etc. that's "better" than GCC.  We have to stick with GCC for most of this because of issues with the codebase we're using from a chipset vendor that doesn't compile right under clang, unfortunately.

**Comment by kraj** [comment]
You can disable libunwind in libcxx add something like below in `local.conf`
```
PACKAGECONFIG_pn-libcxx_remove = "unwind"
```

**Comment by madscientist42** [comment]
Does that cripple the unwind support?

**Comment by kraj** [comment]
it might you have to try

**Comment by madscientist42** [comment]
Nod.  So far it doesn't seem to turn off the unwind support (Annoying...)- trying to figure out what might be off for further info, etc. for the issue.  Will advise shortly.

**Comment by madscientist42** [comment]
Doesn't work with the suggested local.conf addition, works fine with a .bbappend for libcxx in my local metadata layers.

We'll see if I can cheat and use the GCC supplied libunwind for the project needing clang support.

**Comment by kraj** [comment]
it was wrongly specified it should be
`
PACKAGECONFIG_remove_pn-libcxx = "unwind"
`

**Comment by madscientist42** [comment]
Heh...  It happens.  Thanks for the update.  I've not messed with the interface there from the local.conf edge so I couldn't see that one.    I'm building now, I'll correct it when I have intel on how the build is progressing.  It _**looks**_ like it's working as intended from start to finish.

**Comment by madscientist42** [comment]
Seems to be that it's MUCH happier.  I've ran into a few other unrelated problems so I can't tell you it fully works right now- so I'll keep people appraised over the next couple of days while I sort out some of the client's self-inflicted woes first...  X-D

**Comment by kraj** [comment]
Sounds good

**Comment by madscientist42** [comment]
Looks like this is a proper workaround.  I've other issues, but I can open another ticket for those.  :D

**Comment by kraj** [comment]
Closing based on above comment. Feel free to reopen if not resolved yet.

**Comment by mabnhdev** [comment]
I'm having the same issue trying to add the CLang toolchain to my sumo x86_64 build.

I tried the workaround given earlier in the thread and it does not seem to make any difference.

I added the following to my local.conf:

PACKAGECONFIG_remove_pn-libcxx = "unwind"

I still get the following:

ERROR: Multiple .bb files are due to be built which each provide libunwind:                                                            | ETA:  0:00:01
  /sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-support/libunwind/libunwind_1.2.1.bb
  /sbox/mabnhdev/exos-yocto-clang/poky/../meta-clang/recipes-devtools/clang/libcxx_git.bb
A list of tasks depending on these providers is shown and may help explain where the dependency comes from.
/sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique dependees:
  /sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-kernel/perf/perf.bb:do_package
  /sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-kernel/perf/perf.bb:do_prepare_recipe_sysroot
/sbox/mabnhdev/exos-yocto-clang/poky/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique dependees:
  /sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-core/packagegroups/packagegroup-core-standalone-sdk-target.bb:do_package_write_rpm
It could be that one recipe provides something the other doesn't and should. The following provider and runtime provider differences may be helpful.
/sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique provides:
  
/sbox/mabnhdev/exos-yocto-clang/poky/meta/recipes-support/libunwind/libunwind_1.2.1.bb has unique rprovides:
  libunwind-staticdev
  libunwind-dev
  ^libunwind-locale-.*
  libunwind-dbg
  libunwind-locale
  libunwind-doc
/sbox/mabnhdev/exos-yocto-clang/poky/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique provides:
  libcxx
/sbox/mabnhdev/exos-yocto-clang/poky/../meta-clang/recipes-devtools/clang/libcxx_git.bb has unique rprovides:
  libcxx-doc
  libcxx
  libcxx-staticdev
  libcxx-dbg
  libcxx-locale
  libcxx-dev
  ^libcxx-locale-.*

**Comment by mabnhdev** [comment]
Update.  Putting 'PACKAGECONFIG_remove_pn-libcxx = "unwind"' in a .bbappend file seems to work.

**Comment by sateesh0457** [comment]
libunwind is not ported to riscv .when i am working with opencv i am getting error libunwind_1.3.1.
Putting 'PACKAGECONFIG_remove_pn-libcxx = "unwind"' in the  libunwind_1.3.1.bb  file but getting same error .so again this line i added local.conf file but it seems same error.
